modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="erste_coole_maki_mod"
version="1.0.0"
displayName="Erste coole maki mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="admin, MCreator"

[[dependencies.erste_coole_maki_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



